name: Sync and Process
on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 * * * *" # 每小时整点运行
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download remote file
        run: curl -o clash.yml https://raw.githubusercontent.com/aiboboxx/clashfree/refs/heads/main/clash.yml

      - name: Process file with sed
        run: |
          # delete tag <pre ...> </pre>
          sed -i '1s/<pre[^>]*>//; /<\/pre>/d' clash.yml
          # unknown ss method
          sed -i 's/cipher: ss/cipher: none/' clash.yml

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add clash.yml
          git commit -m "feat: update clash.yml" || echo "No changes to commit"
          git push
